name: Kivy Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build APK
      uses: digreatbrian/buildozer-action@v2
      with:
        python-version: 3.12 # Or your desired Python version
        buildozer-cmd: buildozer -v android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: ./bin/*.apk
